### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by maralorn**
I read your changes and new examples and I like them a lot. Implementing static
and dynamic effects and even mixes of it seem so much easier than in other
effect systems.

Wondering a bit about the `Handle` type class. Seems a bit unfortunate that we
need a typeclass just for aligning types the right way. But if we do should it
get a bit of documentation that it is recommended to implement it for your own
handles?

### CODE REVIEW

**Comment by tomjaguarpaw** [comment]
I would say it's unfortunate that you have to massage handles and effects into the right format when defining your own handler, yes. It's quite fiddly to get the "subtyping" relation to work out ergonomically. It's more important to make it ergonomic when defining effectful operations than when defining handlers, so I think we're stuck with it in this case. Given that we're stuck with it, the `Handle` type class seems important, because otherwise you have to have a specialised function for each handle.

I added an explanation of how to add your own `Handle` instances: https://hackage.haskell.org/package/bluefin-0.0.4.2/docs/Bluefin-Compound.html#g:9

**Comment by tomjaguarpaw** [comment]
Yeah, if they're defined but not used I think it will just confuse people. People will eventually see "no instance Handle ..." and then I hope they'll come to the `Handle` docs and everything will be clear.

Thanks again for prompting all these improvements.

**Comment by maralorn** [comment]
> People will eventually see "no instance Handle ..."

True, although that might happen with an effect that someone else defined. So if you publish an effect in an library as a good ecosystem citizen you should implement Handle for it.

> Thanks again for prompting all these improvements.

Thanks for writing bluefin and reacting so promptly to all my qestions.

**Comment by tomjaguarpaw** [comment]
> that might happen with an effect that someone else defined. So if you publish an effect in an library as a good ecosystem citizen you should implement Handle for it.

Ah yes, that's right.

**Pull request merged**
